---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Executing nodest
  shell: |
    pm2 stop default

- name: Executing node
  shell: |
    pm2 start npm -- start
