---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm", "tar", "gzip"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Extract Artifact"
  become: true
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "Copy .env"
  copy:
    src: /home/circleci/project/.env
    dest: /home/ubuntu/

- name: "Copy package"
  copy:
    src: /home/circleci/project/backend/package.json
    dest: /home/ubuntu/

- name: Executing node
  shell: |
    cd /home/ubuntu
    ls
    pm2 start npm -- start
