---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: files/artifact.tar.gz
    dest: /home/ubuntu

- name: Executing node
  shell: |
    cd /home/ubuntu
    pm2 start npm -- start
